; PlatformIO configuration
; LilyGO T-Echo: nRF52840 + SX1262
; Helium LoRaWAN EU868 with RadioLib

[platformio]
default_envs = t-echo

[env:t-echo]
platform = nordicnrf52
board = nrf52840_dk_adafruit
framework = arduino

upload_protocol = nrfutil
monitor_speed = 115200

lib_deps =
    zinggjm/GxEPD2@^1.4.5
    mikalhart/TinyGPSPlus@^1.0.3
    jgromes/RadioLib@^7.7.1
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BME280 Library
    bblanchon/ArduinoJson@^6.21.6
    lewisxhe/PCF8563_Library
    adafruit/Adafruit SPIFlash