[platformio]
default_envs = t-echo

[env:t-echo]
platform = nordicnrf52
board = nrf52840_dk_adafruit
framework = arduino

upload_protocol = nrfutil
monitor_speed = 115200

; Compile only the new combined firmware.
build_src_filter =
    +<main.cpp>
    -<sh_bme280.cpp>
    -<sh_board.cpp>
    -<sh_gps.cpp>
    -<sh_logo.cpp>
    -<sh_lora.cpp>

lib_deps =
    mikalhart/TinyGPSPlus@^1.0.3
    jgromes/RadioLib@^7.7.1
      zinggjm/GxEPD2@^1.6.9